services:
  server:
    build: ./server
    container_name: server_c
    ports:
      - '8000:8000'
    volumes:
      - ./server:/server
      - /home/hulk/Desktop/projects/E-commerce-mern/server/node_modules
  client:
    build: ./client
    container_name: client_c
    ports:
      - '5173:5173'
    volumes:
      - ./client:/client
      - /home/hulk/Desktop/projects/E-commerce-mern/client/node_modules
